In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('crop_dataset.csv')
print(df.columns)

Index(['State_Name', 'Crop_Type', 'Crop', 'N', 'P', 'K', 'pH', 'rainfall',
       'temperature', 'Area_in_hectares', 'Production_in_tons',
       'Yield_ton_per_hec'],
      dtype='object')


In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40658 entries, 0 to 40657
Data columns (total 12 columns):
State_Name            40658 non-null object
Crop_Type             40658 non-null object
Crop                  40658 non-null object
N                     40658 non-null int64
P                     40658 non-null int64
K                     40658 non-null int64
pH                    40658 non-null float64
rainfall              40658 non-null float64
temperature           40658 non-null float64
Area_in_hectares      40658 non-null float64
Production_in_tons    40658 non-null float64
Yield_ton_per_hec     40658 non-null float64
dtypes: float64(6), int64(3), object(3)
memory usage: 3.7+ MB


In [4]:
state_encoder = LabelEncoder()
type_encoder = LabelEncoder()
crop_encoder = LabelEncoder()
df["State_Name"] = state_encoder.fit_transform(df["State_Name"])
df["Crop_Type"] = type_encoder.fit_transform(df["Crop_Type"])
df["Crop"] = crop_encoder.fit_transform(df["Crop"])

In [5]:
X = df.drop(['Crop','Production_in_tons','Yield_ton_per_hec'], axis=1)
y = df['Crop']

In [6]:
models = []
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.20,random_state=32)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((32526, 9), (8132, 9), (32526,), (8132,))

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score

In [8]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 42)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy =accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

[[2020    0    0    0    0]
 [   0 1306    0    0    0]
 [   0    0 2301    0    0]
 [   0    0    0 1251    3]
 [   9    0    1    1 1240]]
Accuracy: 1.00


In [9]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy =accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

[[2020    0    0    0    0]
 [   0 1306    0    0    0]
 [   0    0 2301    0    0]
 [   0    0    0 1254    0]
 [   0    0    0    0 1251]]
Accuracy: 1.00


In [10]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 4, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy =accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

[[2020    0    0    0    0]
 [   0 1306    0    0    0]
 [   0    0 2301    0    0]
 [   0    0    0 1254    0]
 [   0    0    0    0 1251]]
Accuracy: 1.00


In [11]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy =accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

[[1585   27  370    9   29]
 [  98  978   96  115   19]
 [ 465   42 1517   23  254]
 [  89  132   81  934   18]
 [  99    8  206    2  936]]
Accuracy: 0.73


In [12]:
from sklearn.svm import SVC
classifier = SVC(C=3.0,kernel = 'poly', random_state = 42)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
# print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy =accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')